### ISSUE TITLE
Storing state in-memory

### ISSUE THREAD

**Issue by eliasmalik** [pbywater/week7-PAJeS#42]
https://github.com/pbywater/week7-PAJeS/blob/master/src/server.js#L14

You're storing information in an object about the requests that come in.

Route handlers should be stateless as far as possible because they will be dealing with requests from different users. You cannot guarantee that consecutive requests will be from the same user, so you are at risk of leaking data from one user to another by using this approach. All state should either be in the DB or in a cookie.

**Comment by joeylouise** [comment]
hey @eliascodes we realised we werent registering the credentials plugin properly so weve now gotten rid of the object so no global state 👍
